CREATE TABLE Inventory (
    InventoryID INT AUTO_INCREMENT PRIMARY KEY,
    BloodType VARCHAR(5) NOT NULL UNIQUE,
    Quantity INT CHECK (Quantity >= 0) NOT NULL,
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


ALTER TABLE Inventory 
ADD COLUMN MinStock INT DEFAULT 10, 
ADD COLUMN StorageLocation VARCHAR(100) DEFAULT 'Main Storage';
