CREATE TABLE Staff (
    StaffID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    ContactNumber VARCHAR(15) UNIQUE NOT NULL,
    Shift VARCHAR(20) NOT NULL
);