CREATE TABLE Staff (
    StaffID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    ContactNumber VARCHAR(15) UNIQUE NOT NULL,
    Shift VARCHAR(20) NOT NULL
);

ALTER TABLE Staff 
ADD COLUMN Username VARCHAR(50) UNIQUE NOT NULL,
ADD COLUMN PasswordHash VARCHAR(255) NOT NULL,
ADD COLUMN AltContactNumber VARCHAR(15) DEFAULT NULL;
